#+TITLE: Source Code Quality impact @@latex:\\@@ on Pull Requests acceptance
#+AUTHOR: Ondřej Kuhejda
* Introduction
** Problem statement
   - Is there some correlation between the source code quality and the pull request acceptance?
   - Which issues/code smells affect the PR acceptance most?
   - Is code quality impact higher in projects that are using some particular programming language?
   - Is there a better code quality in projects which are using linters as part of their CI?
   - Is there a better code quality in projects which are using linters as part of their build process?
   - Does code smells lead to a longer discussion about PR?
* TODO Pull-based development
  - Wait for It: Determinants of Pull Request Evaluation Latency on GitHub[[cite:latency]]
    - CI and latency
* TODO Code quality
  Trautsch et al.[[cite:pmd]] analyzed several open-source projects in regards to
  usage of static analysis tools.  They found out that incorporating a static
  analysis tool in a build process reduces the defect density.
* Pull request acceptance
  Pull request acceptance is a problem that has been studied multiple
  times. Several surveys were performed in order to understand why pull requests
  are being rejected.

  Gousios et al.[[cite:integrator]] surveyed hundreds of integrators to find out
  their reasons behind the PR rejection. Code quality was stated as the main
  reason by most of the integrators; code style was in the second place.
  Factors that integrators examine the most when evaluating the code quality are
  style conformance and test coverage.

  Kononenko et al.[[cite:shopify]] performed a study of an open-source project
  called /Shopify/; they manually analyzed PR's and also surveyed /Shopify/
  developers. They found out that developers associate the quality of PR with
  the quality of its description and with the revertability and complexity of
  the PR.

  The reasons why contributors abandon their PRs were also
  studied[[cite:abandonment]]. The reason number one was the ``Lack of answers from
  integrators.''; moreover, the ``Lack of time'' and the ``Pull request is
  obsolete'' was also often stated as the main reason.

  Even though the different open-source communities solve the problem of pull
  request acceptance in a different manner, three main governance styles can be
  identified --- protective, equitable, lenient. Protective governance style
  values trust in the contributor-maintainer relationship. The equitable
  governance style tries to be unbiased towards the contributors, and the
  lenient style prioritizes the growth and openness of the community[[cite:foss]].
  Each style focuses on different aspects of PR. Tsay et al.[[cite:social]]
  identified the following levels of social and technical factors that influence
  the acceptance of the PR --- /repository level/, /submitter level/, and the
  /pull request level/.
** Repository level
   The /repository level/ is interested in the aspects of the repository itself,
   such as the repository age, number of collaborators, or number of stars on
   the GitHub.

   For instance, the programming language used in the project also influences
   the acceptance of the PRs. Pull requests containing Java, JavaScript, or C++
   code have a smaller chance to be accepted than PRs containing the code
   written in Go or Scala[[cite:factors]].

   Furthermore, older projects and projects with a large team have a
   significantly lower acceptance rate[[cite:social]].

   The popularity of the project also influences the acceptance rate ---
   projects with more stars have more rejected PRs[[cite:social]].
** Submitter level
   The /submitter level/ is concerned about the submitter's status in the
   general community and his status in the project itself. There are several
   parameters that can be considered when evaluating the submitter's status.

   PRs of submitters with higher social connection to the project have a higher
   probability of being accepted[[cite:social]].

   Submitter status in the general community plays an important role in PR
   acceptance. If the submitter is also a project collaborator, the likelihood
   that the PR will be accepted increases by 63.3%[[cite:social]].

   Moreover, users that contributed to a larger number of projects have a higher
   chance that their PR will be accepted[[cite:npm2]].

   The gender of the submitter is another factor that plays a role in PR
   acceptance. A study showed that woman's PR are accepted more often, but only
   when they are not identifiable as a woman[[cite:gender]].

   Personality traits also influence PR acceptance. The /IBM Watson Personality
   Insights/ were used to obtain the personality traits of the PR submitters by
   analyzing the user's comments. These traits were then used to study PR
   acceptance. It has been shown that conscientiousness, neuroticism, and
   extroversion are traits that have positive effects on PR acceptance. The
   chance that PR will be accepted is also higher when the submitter and closer
   have different personalities[[cite:personality]].
** Pull request level
   The /pull request level/ is interested in the data that are connected to the
   PR itself.  For instance, on the /PR level/, one can study if there is
   a correlation between PR acceptance and the number of GitHub comments in
   the PR. Another parameter that can be used is ``Number of Files Changed'' or
   ``Number of Commits''.

   One of the factors that negatively influence the acceptance rate is the
   already mentioned number of commits in the pull request. The high number of
   commits decreases the probability of acceptance. On the other hand, PR's with
   only one commit are exceptions --- they have a smaller chance to be accepted
   than pull requests which contain two commits[[cite:npm2]].

   Another observation is that more discussed PR's has a smaller chance to be
   accepted[[cite:social]].  Another study did not find a large difference between
   accepted and rejected PR's based on the number of comments but found that
   discussions in rejected PR's have a longer duration[[cite:discussion]].

   Proper testing is the crucial part of every project, and therefore it also
   influences the pull request acceptance.  PR's including more tests have a
   higher chance to be accepted, and an increasing number of changed lines
   decreases the likelihood of PR acceptance[[cite:social]].

   Testing plays a significant role in discovering bugs and therefore leads to
   higher code quality. On the other hand, many test cases do not have
   to mean that code has a high quality. The code quality is an essential
   factor on the /pull request level/, therefore, is this study's main interest.
   Works that are also interested in the code quality and the pull
   request acceptance are examined in the following chapter.

   Another factor that is closely tied to code quality is the code style.
   This factor has a small (but not negligible) negative effect on
   acceptance. This means that PRs with larger code style inconsistency
   (with the codebase) have a smaller chance of being accepted[[cite:style]].
** TODO Code quality
   Although most integrators view code quality as the most important factor
   regarding PR acceptance, to the best of my knowledge, only one study was
   performed to discover whether there is a connection between the PR's
   acceptance and its quality.
   - Does code quality affect pull request acceptance?[[cite:quality]]
** TODO Unsorted
   - study ``Influence of Social and Technical Factors''[[cite:social]] was replicated[[cite:personality]]
   - Replication Can Improve Prior Results: A GitHub Study of Pull Request Acceptance[[cite:replication]]
     - contains interesting table with factors that influences acceptance
   - Pull Request Decision Explained: An Empirical Overview[[cite:empirical]]
     - also contains interesting table with factors that influences acceptance
   - An Exploratory Study of the Pull-Based Software Development Model[[cite:explaratory]]
   - Which Pull Requests Get Accepted and Why? A study of popular NPM Packages[[cite:npm]]
   - Rejection Factors of Pull Requests Filed by Core Team Developers in Software Projects with High Acceptance Rates[[cite:developers]]
   - Pull Request Prioritization Algorithm based on Acceptance and Response Probability[[cite:prioritization]]
* TODO Data sets
  - https://dl.acm.org/doi/abs/10.1145/2597073.2597122
  - https://dl.acm.org/doi/abs/10.1145/3379597.3387489
  - https://zenodo.org/record/3858046
  - https://github.com/XLipcak/rev-rec
  - https://ghtorrent.org/
  - Kalliamvakou et al. noted that data about PR's mined from GitHub are not always reliable,
    because PR can be also merged using several different approaches.
    - https://dl.acm.org/doi/10.1145/2597073.2597074
    - [[cite:explaratory]]
* Evaluation
* Threads to validity
* Conclusion
** Future work
* Setup :noexport:
#+LATEX_CLASS: fithesis4
#+LATEX_CLASS_OPTIONS: [digital,oneside,oldtable,nolof,nolot,nocover]
#+LATEX_HEADER: \usepackage{style}
#+BIND: org-latex-title-command ""
#+BIND: org-latex-toc-command ""
#+BIND: org-latex-with-hyperref nil
#+BIND: org-latex-listings minted
#+BIND: org-src-preserve-indentation nil
#+BIND: org-edit-src-content-indentation 0
# Local Variables:
# mode: org
# org-export-allow-bind-keywords: t
# org-latex-classes: '("fithesis4" "\\documentclass{fithesis4}
#                            [NO-DEFAULT-PACKAGES]
#                            [NO-PACKAGES]"
#                        ("\\chapter{%s}" . "\\chapter*{%s}")
#                        ("\\section{%s}" . "\\section*{%s}")
#                        ("\\subsection{%s}" . "\\subsection*{%s}")
#                        ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
#                        ("\\paragraph{%s}" . "\\paragraph*{%s}")
#                        ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))
# org-latex-pdf-process: ("pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"
#                         "biber %b"
#                         "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"
#                         "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f")
# display-line-numbers-width: 4
# eval: (org-add-link-type "cite"
#         (defun follow-cite (name))
#         (defun export-cite (path desc format)
#           (if (eq format 'latex)
#           (if (or (not desc) (equal 0 (search "cite:" desc)))
#             (format "~\\cite{%s}" path)
#             (format "~\\cite[%s]{%s}" desc path)))))
# End:
